name: Staticmajor
on: [push,workflow_dispatch,pull_request]
jobs:
  run_staticmajor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Staticmajor action
        id: staticmajor
        uses: orijtech/staticmajor-action@main
        with:
            fuzzy: 'true'
            packages: ./leak
